#!/bin/bash
set -xe

cat /opt/collectd-build/sfx_scripts/pbuilderrc > ~/.pbuilderrc

rm -rf /opt/workspace/*
mkdir -p /opt/workspace/collectd

cd /opt/workspace/collectd

rm -rf /opt/collectd/debian/
cp -rf /opt/collectd-build/debian/ .
cp -rf /opt/collectd/* .

sed -i 's/trusty/'${DISTRIBUTION}'/g' debian/changelog

if [ "$DISTRIBUTION" = "precise" ] || [ "$DISTRIBUTION" = "wheezy" ]; then
patch -p0 < debian/patches/precise_control.patch
patch -p0 < debian/patches/precise_rules.patch
fi

#patch version-gen.sh
VERSION_TAG="$(head -1 debian/changelog | awk -F"[-~]" 'NF>2{print $2}')"

_NEW_VERSION=$(grep DEFAULT_VERSION= version-gen.sh  | awk -F\" '{ print $2; }' | perl -p -e "s/git/$VERSION_TAG/g;")
cat <<HERE > version-gen.sh
#!/bin/sh
printf "$_NEW_VERSION"
HERE

chmod 755 version-gen.sh

./build.sh
DIST=${DISTRIBUTION} ARCH=amd64 yes | debuild -us -uc -S
rm -rf /opt/result/*
mkdir -p /opt/result/debuild
cp -rf ../* /opt/result/debuild/
rm -rf /var/cache/pbuilder/*
sudo DIST=${DISTRIBUTION} ARCH=amd64 pbuilder create
DIST=${DISTRIBUTION} ARCH=amd64 pdebuild /opt/result/debuild/*.dsc
mkdir -p /opt/result/pdebuild/
cp /var/cache/pbuilder/${DISTRIBUTION}-amd64/result/* /opt/result/pdebuild/
rm -rf /var/cache/pbuilder/*
cd ..
#rm -rf collectd_*
rm -rf /opt/result/debuild/collectd