#!/bin/bash -ex
#This script is to build the collectd in Jenkins. It need the environment variables JOB_NAME and BASE_DIR.

if [ "$CI" == true ]; then
  tempfolder=$(mktemp -d $(pwd)/0.XXXXXX)
  trap "rm -rf $tempfolder" EXIT
  #Build the packages
  docker run --privileged --name ${JOB_NAME} -e "DISTRIBUTION=${DISTRIBUTION}" -t -v ${BASE_DIR}/collectd:/opt/collectd -v ${BASE_DIR}/collectd-build-ubuntu/build-collectd:/opt/collectd-build -v ${BASE_DIR}/workspace:/opt/workspace -v ${BASE_DIR}/$(basename $tempfolder):/opt/result -v ${BASE_DIR}/pbuilder:/var/cache/pbuilder quay.io/signalfuse/collectd-build-ubuntu /opt/collectd-build/sfx_scripts/cmdseq
else
  if ! [ -z $JOB_NAME ] && ! [ -z $BASE_DIR ]; then
    tempfolder=$(mktemp -d $(pwd)/0.XXXXXX)
    trap "rm -rf $tempfolder; docker rm ${JOB_NAME}" EXIT
    #Build the packages
    docker run --privileged --name ${JOBT_NAME} -e "DISTRIBUTION=${DISTRIBUTION}" -t -v ${BASE_DIR}/${JOB_NAME}/collectd:/opt/collectd -v ${BASE_DIR}/${JOB_NAME}/collectd-build-ubuntu/build-collectd:/opt/collectd-build -v ${BASE_DIR}/${JOB_NAME}/workspace:/opt/workspace -v ${BASE_DIR}/${JOB_NAME}/$(basename $tempfolder):/opt/result -v ${BASE_DIR}/${JOB_NAME}/pbuilder:/var/cache/pbuilder quay.io/signalfuse/collectd-build-ubuntu /opt/collectd-build/sfx_scripts/cmdseq
  else
    exit 1;
  fi
fi

if ! [ -z $BUILD_PUBLISH ] && [ $BUILD_PUBLISH = True ]; then
      OUTPUT=$tempfolder
      # Upload the packages to Amazon S3 bucket
      aws s3 rm --recursive s3://collectd-builds-ubuntu/collectd/${DISTRIBUTION}
      aws s3 cp --recursive $OUTPUT s3://collectd-builds-ubuntu/collectd/${DISTRIBUTION}
fi
exit 0;
