#!/usr/bin/env groovy

stage 'Build all Collectds'
parallel (
    "Build Ubuntu 1204": {
                             node {
                                     parallel (
                                       phase1: { checkout([$class: 'GitSCM', branches: [[name: 'collectd-5.5.1-sfx']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'collectd']], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:signalfx/collectd.git']]]) },
                                       phase2: { checkout([$class: 'GitSCM', branches: [[name: 'blueocean']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:signalfx/collectd-build-ubuntu.git']]]) }
                                     )
                                     sh returnStatus: true, script: '''#!/bin/sh
                                     export BASE_DIR="/storage/disk1/jenkins/workspace"
                                     export DISTRIBUTION="precise"
                                     build-collectd/sfx_scripts/jenkins-build'''
                                   }
                           },
    "Build Ubuntu 1404": {
                             node {
                                     parallel (
                                       phase1: { checkout([$class: 'GitSCM', branches: [[name: 'collectd-5.5.1-sfx']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'collectd']], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:signalfx/collectd.git']]]) },
                                       phase2: { checkout([$class: 'GitSCM', branches: [[name: 'blueocean']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:signalfx/collectd-build-ubuntu.git']]]) }
                                     )
                                     sh returnStatus: true, script: '''#!/bin/sh
                                     export BASE_DIR="/storage/disk1/jenkins/workspace"
                                     export DISTRIBUTION="trusty"
                                     build-collectd/sfx_scripts/jenkins-build'''
                                   }
                           },
)
